spring:
  application:
    name: pedidos
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5555/icompras_pedidos}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
server:
  port: 8080

icompras:
  pedidos:
    clients:
      produtos:
        url: ${MS_PRODUTOS:http://localhost:8081/api/v1/produtos}
      clientes:
        url: ${MS_CLIENTES:http://localhost:8082/api/v1/clientes}
      stripe:
        url: ${STRIPE_GATEWAY:http://localhost:3001/api/v3/payments}